export const REPLACE_INTRODUCTION: string = "REPLACE_INTRODUCTION";
export const INTRODUCTION_LOADING: string = "INTRODUCTION_LOADING";
export const INTRODUCTION_FAILED: string = "INTRODUCTION_FAILED";

export const REPLACE_EDUCATION: string = "REPLACE_EDUCATION";
export const EDUCATION_LOADING: string = "EDUCATION_LOADING";
export const EDUCATION_FAILED: string = "EDUCATION_FAILED";

export const REPLACE_EXPERIENCE: string = "REPLACE_EXPERIENCE";
export const EXPERIENCE_LOADING: string = "EXPERIENCE_LOADING";
export const EXPERIENCE_FAILED: string = "EXPERIENCE_FAILED";

export const REPLACE_QUALIFICATION: string = "REPLACE_QUALIFICATION";
export const QUALIFICATION_LOADING: string = "QUALIFICATION_LOADING";
export const QUALIFICATION_FAILED: string = "QUALIFICATION_FAILED";

export const REPLACE_PORTFOLIO: string = "REPLACE_PORTFOLIO";
export const PORTFOLIO_LOADING: string = "PORTFOLIO_LOADING";
export const PORTFOLIO_FAILED: string = "PORTFOLIO_FAILED";

export const FETCH_ERROR_MESSAGE: string = "ERROR 404: Content not found."
